/**
 * Build script for docs-content
 *
 * Generates src/generated/index.ts with pre-computed navigation and content.
 * This removes the dependency on Vite's import.meta.glob, making the package
 * work in any runtime (Bun, Node, etc).
 *
 * Run:
 *   bun scripts/build.ts
 *   bun scripts/build.ts --validate-only
 */

import { readdir, mkdir, writeFile } from "node:fs/promises"
import { join } from "node:path"
import type { DocsContent, NavSection } from "../src/types"
import { snapshotDocsContent } from "./syntax"

const SRC_DIR = join(import.meta.dir, "../src")
const CONTENT_DIR = join(SRC_DIR, "content")
const GENERATED_DIR = join(SRC_DIR, "generated")

interface ContentEntry {
	filePath: string
	sectionOrder: number
	sectionName: string
	pageOrder: number
	pageName: string
	slug: string
	content: DocsContent
}

type BuildOptions = {
	validateOnly?: boolean
}

async function discoverContentFiles(): Promise<string[]> {
	const files: string[] = []
	const sections = await readdir(CONTENT_DIR)

	for (const section of sections) {
		if (!section.match(/^\d+-/)) continue
		const sectionPath = join(CONTENT_DIR, section)
		const pages = await readdir(sectionPath)

		for (const page of pages) {
			if (!page.endsWith(".ts")) continue
			files.push(join(sectionPath, page))
		}
	}

	return files
}

function parseContentPath(
	filePath: string,
): { sectionOrder: number; sectionName: string; pageOrder: number; pageName: string } | null {
	// Path format: .../content/01-getting-started/02-installation.ts
	const match = filePath.match(/\/(\d+)-([^/]+)\/(\d+)-([^.]+)\.ts$/)
	if (!match) return null

	const [, sectionOrderStr, sectionName, pageOrderStr, pageName] = match
	return {
		sectionOrder: parseInt(sectionOrderStr, 10),
		sectionName,
		pageOrder: parseInt(pageOrderStr, 10),
		pageName,
	}
}

function generateSlug(sectionName: string, pageName: string): string {
	// helpers section files get "helpers-" prefix, others use filename directly
	return sectionName === "helpers" ? `helpers-${pageName}` : pageName
}

function toTitleCase(str: string): string {
	return str
		.split("-")
		.map((word) => word.charAt(0).toUpperCase() + word.slice(1))
		.join(" ")
}

async function loadContentEntries(): Promise<ContentEntry[]> {
	const files = await discoverContentFiles()
	const entries: ContentEntry[] = []

	for (const filePath of files) {
		const parsed = parseContentPath(filePath)
		if (!parsed) continue

		const slug = generateSlug(parsed.sectionName, parsed.pageName)

		// Import the module
		const module = await import(filePath)

		// Find the DocsContent export (first export matching the shape)
		const content = Object.values(module).find(
			(val): val is DocsContent =>
				val !== null && typeof val === "object" && "title" in val && "sections" in val,
		)

		if (!content) {
			console.warn(`No DocsContent export found in ${filePath}`)
			continue
		}

		const snapshotted = await snapshotDocsContent(content, {
			filePath,
			slug,
		})

		entries.push({
			filePath,
			...parsed,
			slug,
			content: snapshotted,
		})
	}

	return entries.sort(
		(a, b) => a.sectionOrder - b.sectionOrder || a.pageOrder - b.pageOrder,
	)
}

function buildNavigation(entries: ContentEntry[]): NavSection[] {
	const sectionMap = new Map<
		string,
		{
			order: number
			title: string
			items: { slug: string; title: string; order: number }[]
		}
	>()

	for (const entry of entries) {
		const sectionTitle = toTitleCase(entry.sectionName)

		if (!sectionMap.has(entry.sectionName)) {
			sectionMap.set(entry.sectionName, {
				order: entry.sectionOrder,
				title: sectionTitle,
				items: [],
			})
		}

		sectionMap.get(entry.sectionName)!.items.push({
			slug: entry.slug,
			title: entry.content.title,
			order: entry.pageOrder,
		})
	}

	return Array.from(sectionMap.values())
		.sort((a, b) => a.order - b.order)
		.map((section) => ({
			title: section.title,
			items: section.items
				.sort((a, b) => a.order - b.order)
				.map((item) => ({
					title: item.title,
					href: `/docs/${item.slug}`,
				})),
		}))
}

function buildContentMap(entries: ContentEntry[]): Record<string, DocsContent> {
	const contentBySlug: Record<string, DocsContent> = {}
	for (const entry of entries) {
		contentBySlug[entry.slug] = entry.content
	}
	return contentBySlug
}

async function generateOutput(entries: ContentEntry[]): Promise<string> {
	const nav = buildNavigation(entries)
	const contentBySlug = buildContentMap(entries)

	const lines: string[] = [
		"/**",
		" * AUTO-GENERATED FILE - DO NOT EDIT",
		" *",
		" * Generated by: bun scripts/build.ts",
		` * Generated at: ${new Date().toISOString()}`,
		" */",
		"",
		'import type { NavSection, DocsContent } from "../types"',
		"",
	]

	// Export navigation
	lines.push("export const docsNav: NavSection[] = " + JSON.stringify(nav, null, "\t"))
	lines.push("")

	// Export content by slug with build-time syntax snapshot payloads
	lines.push(
		"export const contentBySlug: Record<string, DocsContent> = " +
			JSON.stringify(contentBySlug, null, "\t"),
	)
	lines.push("")

	return lines.join("\n")
}

export async function runBuild(options: BuildOptions = {}): Promise<void> {
	console.log("Building docs-content...")

	const entries = await loadContentEntries()
	console.log(`Loaded ${entries.length} content files`)

	if (options.validateOnly) {
		console.log("Syntax validation passed")
		return
	}

	const output = await generateOutput(entries)

	await mkdir(GENERATED_DIR, { recursive: true })
	const outputPath = join(GENERATED_DIR, "index.ts")
	await writeFile(outputPath, output)

	console.log(`Generated: ${outputPath}`)
	console.log("Done!")
}

async function main() {
	const validateOnly = process.argv.includes("--validate-only")
	await runBuild({ validateOnly })
}

if (import.meta.main) {
	main().catch((err) => {
		console.error("Build failed:", err)
		process.exit(1)
	})
}
