/**
 * Build script for docs-content
 *
 * Generates src/generated/index.ts with pre-computed navigation and content.
 * This removes the dependency on Vite's import.meta.glob, making the package
 * work in any runtime (Bun, Node, etc).
 *
 * Run: bun scripts/build.ts
 */

import { readdir, mkdir, writeFile } from "node:fs/promises"
import { join, dirname } from "node:path"
import type { DocsContent, NavSection } from "../src/types"

const SRC_DIR = join(import.meta.dir, "../src")
const CONTENT_DIR = join(SRC_DIR, "content")
const GENERATED_DIR = join(SRC_DIR, "generated")

interface ContentEntry {
	sectionOrder: number
	sectionName: string
	pageOrder: number
	pageName: string
	slug: string
	content: DocsContent
	importPath: string
	exportName: string
}

async function discoverContentFiles(): Promise<string[]> {
	const files: string[] = []
	const sections = await readdir(CONTENT_DIR)

	for (const section of sections) {
		if (!section.match(/^\d+-/)) continue
		const sectionPath = join(CONTENT_DIR, section)
		const pages = await readdir(sectionPath)

		for (const page of pages) {
			if (!page.endsWith(".ts")) continue
			files.push(join(sectionPath, page))
		}
	}

	return files
}

function parseContentPath(
	filePath: string,
): { sectionOrder: number; sectionName: string; pageOrder: number; pageName: string } | null {
	// Path format: .../content/01-getting-started/02-installation.ts
	const match = filePath.match(/\/(\d+)-([^/]+)\/(\d+)-([^.]+)\.ts$/)
	if (!match) return null

	const [, sectionOrderStr, sectionName, pageOrderStr, pageName] = match
	return {
		sectionOrder: parseInt(sectionOrderStr, 10),
		sectionName,
		pageOrder: parseInt(pageOrderStr, 10),
		pageName,
	}
}

function generateSlug(sectionName: string, pageName: string): string {
	// helpers section files get "helpers-" prefix, others use filename directly
	return sectionName === "helpers" ? `helpers-${pageName}` : pageName
}

function toTitleCase(str: string): string {
	return str
		.split("-")
		.map((word) => word.charAt(0).toUpperCase() + word.slice(1))
		.join(" ")
}

async function loadContentEntries(): Promise<ContentEntry[]> {
	const files = await discoverContentFiles()
	const entries: ContentEntry[] = []

	for (const filePath of files) {
		const parsed = parseContentPath(filePath)
		if (!parsed) continue

		// Import the module
		const module = await import(filePath)

		// Find the DocsContent export (first export matching the shape)
		const content = Object.values(module).find(
			(val): val is DocsContent =>
				val !== null && typeof val === "object" && "title" in val && "sections" in val,
		)

		if (!content) {
			console.warn(`No DocsContent export found in ${filePath}`)
			continue
		}

		// Generate export name from filename
		// Helpers section files have "helpers" prefix (e.g., "01-overview" -> "helpersOverviewContent")
		// Other sections use camelCase filename (e.g., "02-installation" -> "installationContent")
		const baseExportName = parsed.pageName
			.split("-")
			.map((word, i) => (i === 0 ? word : word.charAt(0).toUpperCase() + word.slice(1)))
			.join("")

		const exportName =
			parsed.sectionName === "helpers"
				? "helpers" + baseExportName.charAt(0).toUpperCase() + baseExportName.slice(1) + "Content"
				: baseExportName + "Content"

		// Relative import path from generated/ to content/
		const relativePath = filePath
			.replace(SRC_DIR, "..")
			.replace(/\.ts$/, "")

		entries.push({
			...parsed,
			slug: generateSlug(parsed.sectionName, parsed.pageName),
			content,
			importPath: relativePath,
			exportName,
		})
	}

	return entries.sort(
		(a, b) => a.sectionOrder - b.sectionOrder || a.pageOrder - b.pageOrder,
	)
}

function buildNavigation(entries: ContentEntry[]): NavSection[] {
	const sectionMap = new Map<
		string,
		{
			order: number
			title: string
			items: { slug: string; title: string; order: number }[]
		}
	>()

	for (const entry of entries) {
		const sectionTitle = toTitleCase(entry.sectionName)

		if (!sectionMap.has(entry.sectionName)) {
			sectionMap.set(entry.sectionName, {
				order: entry.sectionOrder,
				title: sectionTitle,
				items: [],
			})
		}

		sectionMap.get(entry.sectionName)!.items.push({
			slug: entry.slug,
			title: entry.content.title,
			order: entry.pageOrder,
		})
	}

	return Array.from(sectionMap.values())
		.sort((a, b) => a.order - b.order)
		.map((section) => ({
			title: section.title,
			items: section.items
				.sort((a, b) => a.order - b.order)
				.map((item) => ({
					title: item.title,
					href: `/docs/${item.slug}`,
				})),
		}))
}

async function generateOutput(entries: ContentEntry[]): Promise<string> {
	const nav = buildNavigation(entries)

	const lines: string[] = [
		"/**",
		" * AUTO-GENERATED FILE - DO NOT EDIT",
		" *",
		" * Generated by: bun scripts/build.ts",
		` * Generated at: ${new Date().toISOString()}`,
		" */",
		"",
		'import type { NavSection, DocsContent } from "../types"',
		"",
	]

	// Import all content files
	for (const entry of entries) {
		lines.push(`import { ${entry.exportName} } from "${entry.importPath}"`)
	}

	lines.push("")

	// Export navigation
	lines.push("export const docsNav: NavSection[] = " + JSON.stringify(nav, null, "\t"))
	lines.push("")

	// Export content by slug
	lines.push("export const contentBySlug: Record<string, DocsContent> = {")
	for (const entry of entries) {
		lines.push(`\t"${entry.slug}": ${entry.exportName},`)
	}
	lines.push("}")
	lines.push("")

	return lines.join("\n")
}

async function main() {
	console.log("Building docs-content...")

	// Load all content entries
	const entries = await loadContentEntries()
	console.log(`Found ${entries.length} content files`)

	// Generate output
	const output = await generateOutput(entries)

	// Ensure generated directory exists
	await mkdir(GENERATED_DIR, { recursive: true })

	// Write generated file
	const outputPath = join(GENERATED_DIR, "index.ts")
	await writeFile(outputPath, output)
	console.log(`Generated: ${outputPath}`)

	console.log("Done!")
}

main().catch((err) => {
	console.error("Build failed:", err)
	process.exit(1)
})
